version: "3.7"
services:

 postgres:
     image: postgres:12.1
     env_file:
       - .env.db
     ports: 
       - '5432:5432'
     volumes:
       - postgres:/var/lib/postgresql/data/
       - backups_data:/var/backups/

 redis:
     image: redis:5.0.7
     ports:
       - '6379:6379'
     volumes:
       - drkiq-redis:/var/lib/redis/data

 backend:
     image: ghcr.io/oleksandrtimoshenko/ruby_on_rails
     volumes:
       - ./:/opt/app
     links:
       - postgres
       - redis
     ports:
       - '8010:8010'
     env_file:
       - .env
     depends_on:
       - postgres
     command: ./entrypoint.sh

 sidekiq:
     image: ghcr.io/oleksandrtimoshenko/ruby_on_rails
     command: bundle exec sidekiq 
     links:
       - postgres
       - redis
     env_file:
       - .env

 nginx:
     image: nginx:1.19.0-alpine
     volumes:
       - nginx-configs:/etc/nginx/conf.d/
     ports:
       - 80:80
     depends_on:
       - backend

volumes:
   postgres:
   backups_data:
   drkiq-redis:
   nginx-configs:
      driver_opts:
        type: none
        #device: /opt/nginx/
        device: /home/alex/my_files/learning_3/Teamvoy/my_projects/ryby-on-rails-app-with-sidekiq/deploy/nginx/
        o: bind
